ekf_node:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf: true
    print_diagnostics: true
    two_d_mode: true

    frequency: 20.0

    odom0: jackal_velocity_controller/odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true, true, false,
                  false, false, true,
                  false, false, false]
    odom0_differential: false
    odom0_queue_size: 10

    imu0: imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
